CREATE DATABASE PROJETOFINALGIL
USE PROJETOFINALGIL


CREATE TABLE CLIENTES
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR (30),
	EMAIL VARCHAR (30),
	TELEFONE VARCHAR (11),
	ENDERECO VARCHAR (90),
	NUMERO INT,
	CIDADE VARCHAR (50), 
	UF VARCHAR (30),
	SEXO VARCHAR (30)
)

GO
drop table CLIENTES

SELECT * FROM CLIENTES 

INSERT INTO CLIENTES VALUES('GILMAR', '@ALUNO.IFSP.EDU.BR', '997990947','CENTRO MONTEIRO LOBATO', 1446, 'CIDADE', 'UF', 'MASCULINO')



create table PROPRIETARIO

(

ID int primary key,
NOME varchar(30),
SEXO CHAR,
CPF VARCHAR(12),
EMAIL VARCHAR(100),
TELEFONE VARCHAR(11),
ENDERECO VARCHAR(60)

)
GO
INSERT INTO PROPRIETARIO VALUES (2, 'JOSE AMANCIO', 'M', '04545694536','amancio@gmail.com', '35367070', 'Rua Florentina Monteiro Lobato')
INSERT INTO PROPRIETARIO VALUES (1, 'GILMAR', 'M','08793364636','mail.com','997990947','CENTRO MONTEIRO LOBATO')
update PROPRIETARIO SET EMAIL = 'gilmar.gomes@aluno.ifsp.edu.br'

WHERE ID = 1
SELECT * FROM PROPRIETARIO;


CREATE TABLE FUNCIONARIOS 
(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SEXO VARCHAR(10) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ADMISSAO DATE NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    DEPARTAMENTO VARCHAR(100) NOT NULL,
    ID_PROPRIETARIO INT NOT NULL,
    FOREIGN KEY (ID_PROPRIETARIO) REFERENCES PROPRIETARIO(ID)
);

DROP TABLE FUNCIONARIOS

INSERT INTO FUNCIONARIOS VALUES ('JENIFER SILVA', 'F','00000000000','2021-02-21', 1900.00, 'CAIXA', 'VENDAS', 1)
INSERT INTO FUNCIONARIOS VALUES ('ISALRA SANTOS', 'F','00000000000','2000-05-22', 2500.00, 'GERENTE', 'ADMINISTRATIVO',1)
INSERT INTO FUNCIONARIOS VALUES ('JOYCE SOUZA', 'F','00000000000','2022-02-22', 1500.00, 'REPOSITOR', 'ESTOQUISTA',1)

SELECT * FROM FUNCIONARIOS



CREATE TABLE produtos_hortifruti
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Descricao TEXT,
    TipoDeItem VARCHAR(50),
    Unidade VARCHAR(20),
    Preco DECIMAL(10, 2),
    Vendas INT,
    Marcas VARCHAR(50),
    Modelo VARCHAR(50),
    CodigoBalanca VARCHAR(20),
    DataVencimento DATE NOT NULL
);
GO
select * from produtos_hortifruti

INSERT INTO produtos_hortifruti VALUES ('Maçã', 'Maçãs frescas colhidas na fazenda local.', 'Fruta', 'Kg', 2.99, 100, 'Marca A', 'Modelo X1', '12345', '2023-04-01');




drop table produtos






DELETE FROM CLIENTES WHERE ID = 1



SELECT *FROM CLIENTES
